image:
  name: registry.new-page.xyz/cloud-builders/bazel

variables:
  GIT_CLEAN_FLAGS: -ffdx -e .cache/

before_script:
  - export HTTP_PROXY=http://hkt.v2ray:1080 HTTPS_PROXY=http://hkt.v2ray:1080
  - echo "build --disk_cache=$CI_PROJECT_DIR/.cache" >> .bazelrc

cache:
  key: bazel_cache
  paths:
    - .cache/

stages:
  - build
  - test

build:
  stage: build
  script:
    - bazel version
    - bazel build ...
test:
  stage: test
  script:
  - bazel test ...