image:
  name: registry.new-page.xyz/cloud-marketplace-containers/google/bazel:3.2.0

variables:
  GIT_CLEAN_FLAGS: -ffdx -e .cache/
  GOPROXY: http://goproxy.golang:8080
  GO111MODULE: "on"

before_script:
  - chmod -R +x build
  - mkdir $HOME/.docker
  - export HTTP_PROXY=http://hkt.v2ray:1080 HTTPS_PROXY=http://hkt.v2ray:1080 NO_PROXY=hkt.v2ray,goproxy.golang,*.new-page.xyz
  - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json

cache:
  key: bazel_cache
  paths:
    - .cache/

stages:
  - build
  - push images
  - deploy

build:
  stage: build
  script:
    - bazel version
    - bazel build --noshow_progress -k //app/... //pkg/...
    - bazel test --noshow_progress -k //app/... //pkg/...
    - build/push-images.sh changed

push all images:
  stage: push images
  script:
    - build/push-images.sh
  when: manual

deploy:
  stage: deploy
  image: registry.new-page.xyz/alpine/helm:3.2.3
  script:
    - mkdir ~/.kube && echo -n $KUBE_CONFIG | base64 -d > ~/.kube/config
    - helm upgrade --install --namespace ncs ncs ./chart
  when: always