image:
  name: registry.new-page.xyz/cloud-marketplace-containers/google/bazel:3.2.0

variables:
  GIT_CLEAN_FLAGS: -ffdx -e .cache/
  GOPROXY: http://nexus3.nexus3:8081/repository/goproxy/
  GOSUMDB: gosum.io+ce6e7565+AY5qEHUk/qmHc5btzW45JVoENfazw8LielDsaI+lEbq6

before_script:
  - chmod -R +x build
  - mkdir $HOME/.docker
  - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json

cache:
  key: bazel_cache
  paths:
    - .cache/

stages:
  - build
  - push images

build:
  stage: build
  script:
    - bazel version
    - bazel build --noshow_progress -k //app/... //pkg/...
    - bazel test --noshow_progress -k //app/... //pkg/...
    - build/push-images.sh changed

push all images:
  stage: push images
  script:
    - build/push-images.sh
  when: manual