image:
  name: registry.new-page.xyz/cloud-builders/bazel:latest

variables:
  GIT_CLEAN_FLAGS: -ffdx -e .cache/

before_script:
  - chmod -R +x build
  - export HTTP_PROXY=http://hkt.v2ray:1080 HTTPS_PROXY=http://hkt.v2ray:1080
  - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json

cache:
  key: bazel_cache
  paths:
    - .cache/

stages:
  - build
  - test
  - push_images

build:
  stage: build
  script:
    - bazel version
    - bazel build //...

test:
  stage: test
  script:
    - bazel version
    - bazel test //...

push_images:
  stage: push_images
  script:
    - bazel version
    - build/push-images.sh
