image:
  name: registry.new-page.xyz/cloud-builders/bazel:latest

variables:
  GIT_CLEAN_FLAGS: -ffdx -e .cache/

before_script:
  - chmod -R +x build
  - export HTTP_PROXY=http://hkt.v2ray:1080 HTTPS_PROXY=http://hkt.v2ray:1080
  - mkdir $HOME/.docker
  - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json

cache:
  key: bazel_cache
  paths:
    - .cache/

stages:
  - build
  - test
  - push images

build:
  stage: build
  script:
    - bazel version
    - bazel build //...

test:
  stage: test
  script:
    - bazel version
    - bazel test //...

push changed images:
  stage: push images
  script:
    - bazel version
    - build/push-images.sh changed
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != "master"
      changes:
      - pkg/*
      - build/*
      - .gitlab-ci.yml
      when: never
    - when: on_success

push all images:
  stage: push images
  script:
    - bazel version
    - build/push-images.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != "master"
      changes:
      - pkg/*
      - build/*
      - .gitlab-ci.yml
      when: manual