image:
  name: registry.new-page.xyz/cloud-marketplace-containers/google/bazel:3.2.0

variables:
  GIT_CLEAN_FLAGS: -ffdx -e .cache/
  GO_REPOSITORY_USE_HOST_CACHE: 1
  GOPATH: ${CI_PROJECT_DIR}/.cache/go

before_script:
  - chmod -R +x build
  - mkdir $HOME/.docker
  - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json

cache:
  key: bazel_cache
  paths:
    - .cache/

stages:
  - build
  - push images

build:
  stage: build
  script:
    - bazel version
    - bazel build --noshow_progress -k //app/... //pkg/...
    - bazel test --noshow_progress -k //app/... //pkg/...
    - build/push-images.sh changed

push all images:
  stage: push images
  script:
    - bazel version
    - build/push-images.sh
  when: manual