image:
  name: registry.new-page.xyz/cloud-marketplace-containers/google/bazel:3.2.0

variables:
  GIT_CLEAN_FLAGS: -ffdx -e .cache/
  GOPROXY: http://goproxy.golang:8080
  GO111MODULE: "on"
  GO_REPOSITORY_USE_HOST_CACHE: 1
  GOPATH: ${CI_PROJECT_DIR}/.cache/go-path
  GOCACHE: ${CI_PROJECT_DIR}/.cache/go-cache

before_script:
  - chmod -R +x build
  - mkdir $HOME/.docker
  - export HTTP_PROXY=http://hkt.v2ray:1080 HTTPS_PROXY=http://hkt.v2ray:1080 NO_PROXY=hkt.v2ray,goproxy.golang,*.new-page.xyz,*.local
  - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json

cache:
  key: bazel_cache
  paths:
    - .cache/

stages:
  - build
  - push images
  - deploy

lint-golang:
  stage: build
  image: registry.new-page.xyz/golangci/golangci-lint:latest-alpine
  script:
    - golangci-lint run -v
  allow_failure: true

lint-helm:
  stage: build
  image: registry.new-page.xyz/alpine/helm:3.2.3
  script:
    - helm lint ./chart
  allow_failure: true

build:
  stage: build
  script:
    - bazel version
    - bazel build --config=ci --noshow_progress -k //app/... //pkg/...
    - bazel test --config=ci --noshow_progress -k //app/... //pkg/...

build-merged:
  stage: build
  script:
    - git config --global user.email "runner@gitlab.com"
    - git config --global user.name "Runner"
    - git pull origin master
    - bazel version
    - bazel build --config=ci --noshow_progress -k //app/... //pkg/...
    - bazel test --config=ci --noshow_progress -k //app/... //pkg/...
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

push changed images:
  stage: push images
  script:
    - build/push-images.sh changed
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

push all images:
  stage: push images
  script:
    - build/push-images.sh
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual

deploy:
  stage: deploy
  image: registry.new-page.xyz/alpine/helm:3.2.3
  script:
    - mkdir ~/.kube && echo -n $KUBE_CONFIG | base64 -d > ~/.kube/config
    - helm upgrade --install --namespace ncs ncs ./chart
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  needs: ["push changed images"]
  cache: {}