// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: app/service/user/title/api/grpc/v1/title.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid         int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	CustomTitle string `protobuf:"bytes,2,opt,name=custom_title,json=customTitle,proto3" json:"custom_title,omitempty"`
	TitleType   int32  `protobuf:"varint,3,opt,name=title_type,json=titleType,proto3" json:"title_type,omitempty"`
}

func (x *Info) Reset() {
	*x = Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_service_user_title_api_grpc_v1_title_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_app_service_user_title_api_grpc_v1_title_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_app_service_user_title_api_grpc_v1_title_proto_rawDescGZIP(), []int{0}
}

func (x *Info) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Info) GetCustomTitle() string {
	if x != nil {
		return x.CustomTitle
	}
	return ""
}

func (x *Info) GetTitleType() int32 {
	if x != nil {
		return x.TitleType
	}
	return 0
}

type GetTitleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *GetTitleReq) Reset() {
	*x = GetTitleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_service_user_title_api_grpc_v1_title_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTitleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTitleReq) ProtoMessage() {}

func (x *GetTitleReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_service_user_title_api_grpc_v1_title_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTitleReq.ProtoReflect.Descriptor instead.
func (*GetTitleReq) Descriptor() ([]byte, []int) {
	return file_app_service_user_title_api_grpc_v1_title_proto_rawDescGZIP(), []int{1}
}

func (x *GetTitleReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetTitleResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *Info `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *GetTitleResp) Reset() {
	*x = GetTitleResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_service_user_title_api_grpc_v1_title_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTitleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTitleResp) ProtoMessage() {}

func (x *GetTitleResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_service_user_title_api_grpc_v1_title_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTitleResp.ProtoReflect.Descriptor instead.
func (*GetTitleResp) Descriptor() ([]byte, []int) {
	return file_app_service_user_title_api_grpc_v1_title_proto_rawDescGZIP(), []int{2}
}

func (x *GetTitleResp) GetInfo() *Info {
	if x != nil {
		return x.Info
	}
	return nil
}

type SetTitleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *Info `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *SetTitleReq) Reset() {
	*x = SetTitleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_service_user_title_api_grpc_v1_title_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTitleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTitleReq) ProtoMessage() {}

func (x *SetTitleReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_service_user_title_api_grpc_v1_title_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTitleReq.ProtoReflect.Descriptor instead.
func (*SetTitleReq) Descriptor() ([]byte, []int) {
	return file_app_service_user_title_api_grpc_v1_title_proto_rawDescGZIP(), []int{3}
}

func (x *SetTitleReq) GetInfo() *Info {
	if x != nil {
		return x.Info
	}
	return nil
}

type SetTitleResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetTitleResp) Reset() {
	*x = SetTitleResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_service_user_title_api_grpc_v1_title_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTitleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTitleResp) ProtoMessage() {}

func (x *SetTitleResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_service_user_title_api_grpc_v1_title_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTitleResp.ProtoReflect.Descriptor instead.
func (*SetTitleResp) Descriptor() ([]byte, []int) {
	return file_app_service_user_title_api_grpc_v1_title_proto_rawDescGZIP(), []int{4}
}

var File_app_service_user_title_api_grpc_v1_title_proto protoreflect.FileDescriptor

var file_app_service_user_title_api_grpc_v1_title_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x61, 0x70, 0x70, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x2f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x19, 0x6e, 0x63, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5a, 0x0a, 0x04, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x1f, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x54, 0x69, 0x74, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x43, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x54, 0x69, 0x74,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6e, 0x63, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x42, 0x0a, 0x0b, 0x53,
	0x65, 0x74, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x33, 0x0a, 0x04, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6e, 0x63, 0x73, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22,
	0x0e, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x32,
	0xff, 0x01, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x76, 0x0a, 0x08, 0x47, 0x65, 0x74,
	0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x26, 0x2e, 0x6e, 0x63, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x27, 0x2e,
	0x6e, 0x63, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x69, 0x74,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x12, 0x11,
	0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x2f, 0x7b, 0x75, 0x69, 0x64,
	0x7d, 0x12, 0x7e, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x26, 0x2e,
	0x6e, 0x63, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x54, 0x69, 0x74,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x27, 0x2e, 0x6e, 0x63, 0x73, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x65, 0x74, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x21,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x1a, 0x16, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x2f, 0x7b, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x75, 0x69, 0x64, 0x7d, 0x3a, 0x01,
	0x2a, 0x42, 0x2c, 0x5a, 0x2a, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x61, 0x70, 0x70,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_service_user_title_api_grpc_v1_title_proto_rawDescOnce sync.Once
	file_app_service_user_title_api_grpc_v1_title_proto_rawDescData = file_app_service_user_title_api_grpc_v1_title_proto_rawDesc
)

func file_app_service_user_title_api_grpc_v1_title_proto_rawDescGZIP() []byte {
	file_app_service_user_title_api_grpc_v1_title_proto_rawDescOnce.Do(func() {
		file_app_service_user_title_api_grpc_v1_title_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_service_user_title_api_grpc_v1_title_proto_rawDescData)
	})
	return file_app_service_user_title_api_grpc_v1_title_proto_rawDescData
}

var file_app_service_user_title_api_grpc_v1_title_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_app_service_user_title_api_grpc_v1_title_proto_goTypes = []interface{}{
	(*Info)(nil),         // 0: ncs.service.user.title.v1.Info
	(*GetTitleReq)(nil),  // 1: ncs.service.user.title.v1.GetTitleReq
	(*GetTitleResp)(nil), // 2: ncs.service.user.title.v1.GetTitleResp
	(*SetTitleReq)(nil),  // 3: ncs.service.user.title.v1.SetTitleReq
	(*SetTitleResp)(nil), // 4: ncs.service.user.title.v1.SetTitleResp
}
var file_app_service_user_title_api_grpc_v1_title_proto_depIdxs = []int32{
	0, // 0: ncs.service.user.title.v1.GetTitleResp.info:type_name -> ncs.service.user.title.v1.Info
	0, // 1: ncs.service.user.title.v1.SetTitleReq.info:type_name -> ncs.service.user.title.v1.Info
	1, // 2: ncs.service.user.title.v1.Title.GetTitle:input_type -> ncs.service.user.title.v1.GetTitleReq
	3, // 3: ncs.service.user.title.v1.Title.SetTitle:input_type -> ncs.service.user.title.v1.SetTitleReq
	2, // 4: ncs.service.user.title.v1.Title.GetTitle:output_type -> ncs.service.user.title.v1.GetTitleResp
	4, // 5: ncs.service.user.title.v1.Title.SetTitle:output_type -> ncs.service.user.title.v1.SetTitleResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_app_service_user_title_api_grpc_v1_title_proto_init() }
func file_app_service_user_title_api_grpc_v1_title_proto_init() {
	if File_app_service_user_title_api_grpc_v1_title_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_service_user_title_api_grpc_v1_title_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_service_user_title_api_grpc_v1_title_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTitleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_service_user_title_api_grpc_v1_title_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTitleResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_service_user_title_api_grpc_v1_title_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetTitleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_service_user_title_api_grpc_v1_title_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetTitleResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_service_user_title_api_grpc_v1_title_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_service_user_title_api_grpc_v1_title_proto_goTypes,
		DependencyIndexes: file_app_service_user_title_api_grpc_v1_title_proto_depIdxs,
		MessageInfos:      file_app_service_user_title_api_grpc_v1_title_proto_msgTypes,
	}.Build()
	File_app_service_user_title_api_grpc_v1_title_proto = out.File
	file_app_service_user_title_api_grpc_v1_title_proto_rawDesc = nil
	file_app_service_user_title_api_grpc_v1_title_proto_goTypes = nil
	file_app_service_user_title_api_grpc_v1_title_proto_depIdxs = nil
}
