// Code generated by MockGen. DO NOT EDIT.
// Source: app/hello/api/grpc/v1/hello_grpc.pb.go

// Package v1 is a generated GoMock package.
package v1

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	reflect "reflect"
)

// MockHelloClient is a mock of HelloClient interface
type MockHelloClient struct {
	ctrl     *gomock.Controller
	recorder *MockHelloClientMockRecorder
}

// MockHelloClientMockRecorder is the mock recorder for MockHelloClient
type MockHelloClientMockRecorder struct {
	mock *MockHelloClient
}

// NewMockHelloClient creates a new mock instance
func NewMockHelloClient(ctrl *gomock.Controller) *MockHelloClient {
	mock := &MockHelloClient{ctrl: ctrl}
	mock.recorder = &MockHelloClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockHelloClient) EXPECT() *MockHelloClientMockRecorder {
	return m.recorder
}

// Hello mocks base method
func (m *MockHelloClient) Hello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloResp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Hello", varargs...)
	ret0, _ := ret[0].(*HelloResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hello indicates an expected call of Hello
func (mr *MockHelloClientMockRecorder) Hello(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hello", reflect.TypeOf((*MockHelloClient)(nil).Hello), varargs...)
}

// MockHelloServer is a mock of HelloServer interface
type MockHelloServer struct {
	ctrl     *gomock.Controller
	recorder *MockHelloServerMockRecorder
}

// MockHelloServerMockRecorder is the mock recorder for MockHelloServer
type MockHelloServerMockRecorder struct {
	mock *MockHelloServer
}

// NewMockHelloServer creates a new mock instance
func NewMockHelloServer(ctrl *gomock.Controller) *MockHelloServer {
	mock := &MockHelloServer{ctrl: ctrl}
	mock.recorder = &MockHelloServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockHelloServer) EXPECT() *MockHelloServerMockRecorder {
	return m.recorder
}

// Hello mocks base method
func (m *MockHelloServer) Hello(arg0 context.Context, arg1 *HelloReq) (*HelloResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hello", arg0, arg1)
	ret0, _ := ret[0].(*HelloResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hello indicates an expected call of Hello
func (mr *MockHelloServerMockRecorder) Hello(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hello", reflect.TypeOf((*MockHelloServer)(nil).Hello), arg0, arg1)
}

// MockUnsafeHelloServer is a mock of UnsafeHelloServer interface
type MockUnsafeHelloServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeHelloServerMockRecorder
}

// MockUnsafeHelloServerMockRecorder is the mock recorder for MockUnsafeHelloServer
type MockUnsafeHelloServerMockRecorder struct {
	mock *MockUnsafeHelloServer
}

// NewMockUnsafeHelloServer creates a new mock instance
func NewMockUnsafeHelloServer(ctrl *gomock.Controller) *MockUnsafeHelloServer {
	mock := &MockUnsafeHelloServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeHelloServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUnsafeHelloServer) EXPECT() *MockUnsafeHelloServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedHelloServer mocks base method
func (m *MockUnsafeHelloServer) mustEmbedUnimplementedHelloServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedHelloServer")
}

// mustEmbedUnimplementedHelloServer indicates an expected call of mustEmbedUnimplementedHelloServer
func (mr *MockUnsafeHelloServerMockRecorder) mustEmbedUnimplementedHelloServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedHelloServer", reflect.TypeOf((*MockUnsafeHelloServer)(nil).mustEmbedUnimplementedHelloServer))
}
