// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SignClient is the client API for Sign service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SignClient interface {
	Info(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*InfoResp, error)
	Sign(ctx context.Context, in *SignReq, opts ...grpc.CallOption) (*SignResp, error)
}

type signClient struct {
	cc grpc.ClientConnInterface
}

func NewSignClient(cc grpc.ClientConnInterface) SignClient {
	return &signClient{cc}
}

func (c *signClient) Info(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*InfoResp, error) {
	out := new(InfoResp)
	err := c.cc.Invoke(ctx, "/ncs.service.user.sign.v1.Sign/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signClient) Sign(ctx context.Context, in *SignReq, opts ...grpc.CallOption) (*SignResp, error) {
	out := new(SignResp)
	err := c.cc.Invoke(ctx, "/ncs.service.user.sign.v1.Sign/Sign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignServer is the server API for Sign service.
// All implementations must embed UnimplementedSignServer
// for forward compatibility
type SignServer interface {
	Info(context.Context, *InfoReq) (*InfoResp, error)
	Sign(context.Context, *SignReq) (*SignResp, error)
	mustEmbedUnimplementedSignServer()
}

// UnimplementedSignServer must be embedded to have forward compatible implementations.
type UnimplementedSignServer struct {
}

func (UnimplementedSignServer) Info(context.Context, *InfoReq) (*InfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedSignServer) Sign(context.Context, *SignReq) (*SignResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sign not implemented")
}
func (UnimplementedSignServer) mustEmbedUnimplementedSignServer() {}

// UnsafeSignServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignServer will
// result in compilation errors.
type UnsafeSignServer interface {
	mustEmbedUnimplementedSignServer()
}

func RegisterSignServer(s grpc.ServiceRegistrar, srv SignServer) {
	s.RegisterService(&Sign_ServiceDesc, srv)
}

func _Sign_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ncs.service.user.sign.v1.Sign/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignServer).Info(ctx, req.(*InfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sign_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ncs.service.user.sign.v1.Sign/Sign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignServer).Sign(ctx, req.(*SignReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Sign_ServiceDesc is the grpc.ServiceDesc for Sign service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sign_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ncs.service.user.sign.v1.Sign",
	HandlerType: (*SignServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _Sign_Info_Handler,
		},
		{
			MethodName: "Sign",
			Handler:    _Sign_Sign_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/service/user/sign/api/grpc/v1/sign.proto",
}
