{{- $fullName := include "chart.fullname" . -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}
spec:
  hosts:
  - {{ $fullName }}
  http:
  - route:
    - destination:
        host: {{ $fullName }}
    retries:
      attempts: 1
      perTryTimeout: 10s
---
