{{- $this := . -}}
{{- range .Values.services}}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .app }}
spec:
  host: {{ .app }}
  subsets:
  - name: {{ .version }}
  labels:
    version: {{ .version }}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
{{- end -}}