{{- $this := . -}}
{{- range .Values.services}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .app }}
  labels:
    {{- /* istio */}}
    app: {{ .app }}
    {{- include "ncs-services.labels" $this | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: {{ .app }}
  ports:
    - port: 2333
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: 23333
      targetPort: health
      protocol: TCP
      name: health
---
{{- end -}}
