{{- $this := . -}}
{{- range .Values.services}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .app }}
  labels:
    {{- /* istio */}}
    app: {{ .app }}
    {{- include "ncs-services.labels" $this | nindent 4 }}
spec:
  type: {{ $this.Values.service.type }}
  ports:
    - port: {{ $this.Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: {{ .app }}
---
{{- end -}}
